---
- hosts: all
  collections:
  # Install a collection from Ansible Galaxy.
  - ansible.tower
  tasks:
  
  - name: Add tower host
    tower_host:
      name: localhost
      description: "Local Host Group"
      inventory: "Local Inventory"
      state: present
      tower_config_file: "~/tower_cli.cfg"
      variables:
        example_var: 123
